/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    name: string;
    /**
     * 
     * @type {AccountType}
     * @memberof AccountResponse
     */
    type: AccountType;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof AccountResponse
     */
    currentBalance: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccountResponse
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the AccountResponse interface.
 */
export function instanceOfAccountResponse(value: object): value is AccountResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('currentBalance' in value) || value['currentBalance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AccountResponseFromJSON(json: any): AccountResponse {
    return AccountResponseFromJSONTyped(json, false);
}

export function AccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': AccountTypeFromJSON(json['type']),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'currentBalance': json['current_balance'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function AccountResponseToJSON(json: any): AccountResponse {
    return AccountResponseToJSONTyped(json, false);
}

export function AccountResponseToJSONTyped(value?: AccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': AccountTypeToJSON(value['type']),
        'description': value['description'],
        'id': value['id'],
        'current_balance': value['currentBalance'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

