/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountType } from './AccountType';
import {
    AccountTypeFromJSON,
    AccountTypeFromJSONTyped,
    AccountTypeToJSON,
    AccountTypeToJSONTyped,
} from './AccountType';

/**
 * 
 * @export
 * @interface AccountBalanceResponse
 */
export interface AccountBalanceResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountBalanceResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AccountBalanceResponse
     */
    name: string;
    /**
     * 
     * @type {AccountType}
     * @memberof AccountBalanceResponse
     */
    type: AccountType;
    /**
     * 
     * @type {number}
     * @memberof AccountBalanceResponse
     */
    currentBalance: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountBalanceResponse
     */
    lastUpdated: Date;
}



/**
 * Check if a given object implements the AccountBalanceResponse interface.
 */
export function instanceOfAccountBalanceResponse(value: object): value is AccountBalanceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('currentBalance' in value) || value['currentBalance'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function AccountBalanceResponseFromJSON(json: any): AccountBalanceResponse {
    return AccountBalanceResponseFromJSONTyped(json, false);
}

export function AccountBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': AccountTypeFromJSON(json['type']),
        'currentBalance': json['current_balance'],
        'lastUpdated': (new Date(json['last_updated'])),
    };
}

export function AccountBalanceResponseToJSON(json: any): AccountBalanceResponse {
    return AccountBalanceResponseToJSONTyped(json, false);
}

export function AccountBalanceResponseToJSONTyped(value?: AccountBalanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': AccountTypeToJSON(value['type']),
        'current_balance': value['currentBalance'],
        'last_updated': ((value['lastUpdated']).toISOString()),
    };
}

