/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailableResponse
 */
export interface AvailableResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AvailableResponse
     */
    available: boolean;
}

/**
 * Check if a given object implements the AvailableResponse interface.
 */
export function instanceOfAvailableResponse(value: object): value is AvailableResponse {
    if (!('available' in value) || value['available'] === undefined) return false;
    return true;
}

export function AvailableResponseFromJSON(json: any): AvailableResponse {
    return AvailableResponseFromJSONTyped(json, false);
}

export function AvailableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'],
    };
}

export function AvailableResponseToJSON(json: any): AvailableResponse {
    return AvailableResponseToJSONTyped(json, false);
}

export function AvailableResponseToJSONTyped(value?: AvailableResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
    };
}

