/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkSaleResponse
 */
export interface BulkSaleResponse {
    /**
     * 
     * @type {number}
     * @memberof BulkSaleResponse
     */
    totalRevenue: number;
    /**
     * 
     * @type {number}
     * @memberof BulkSaleResponse
     */
    salesCount: number;
}

/**
 * Check if a given object implements the BulkSaleResponse interface.
 */
export function instanceOfBulkSaleResponse(value: object): value is BulkSaleResponse {
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('salesCount' in value) || value['salesCount'] === undefined) return false;
    return true;
}

export function BulkSaleResponseFromJSON(json: any): BulkSaleResponse {
    return BulkSaleResponseFromJSONTyped(json, false);
}

export function BulkSaleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkSaleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRevenue': json['total_revenue'],
        'salesCount': json['sales_count'],
    };
}

export function BulkSaleResponseToJSON(json: any): BulkSaleResponse {
    return BulkSaleResponseToJSONTyped(json, false);
}

export function BulkSaleResponseToJSONTyped(value?: BulkSaleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_revenue': value['totalRevenue'],
        'sales_count': value['salesCount'],
    };
}

