/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CapacityAnalysisEvent } from './CapacityAnalysisEvent';
import {
    CapacityAnalysisEventFromJSON,
    CapacityAnalysisEventFromJSONTyped,
    CapacityAnalysisEventToJSON,
    CapacityAnalysisEventToJSONTyped,
} from './CapacityAnalysisEvent';

/**
 * 
 * @export
 * @interface CapacityAnalysisResponse
 */
export interface CapacityAnalysisResponse {
    /**
     * 
     * @type {Array<CapacityAnalysisEvent>}
     * @memberof CapacityAnalysisResponse
     */
    capacityAnalysis: Array<CapacityAnalysisEvent>;
}

/**
 * Check if a given object implements the CapacityAnalysisResponse interface.
 */
export function instanceOfCapacityAnalysisResponse(value: object): value is CapacityAnalysisResponse {
    if (!('capacityAnalysis' in value) || value['capacityAnalysis'] === undefined) return false;
    return true;
}

export function CapacityAnalysisResponseFromJSON(json: any): CapacityAnalysisResponse {
    return CapacityAnalysisResponseFromJSONTyped(json, false);
}

export function CapacityAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapacityAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'capacityAnalysis': ((json['capacity_analysis'] as Array<any>).map(CapacityAnalysisEventFromJSON)),
    };
}

export function CapacityAnalysisResponseToJSON(json: any): CapacityAnalysisResponse {
    return CapacityAnalysisResponseToJSONTyped(json, false);
}

export function CapacityAnalysisResponseToJSONTyped(value?: CapacityAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capacity_analysis': ((value['capacityAnalysis'] as Array<any>).map(CapacityAnalysisEventToJSON)),
    };
}

