/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyBreakdown
 */
export interface DailyBreakdown {
    /**
     * 
     * @type {string}
     * @memberof DailyBreakdown
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof DailyBreakdown
     */
    revenue: number;
    /**
     * 
     * @type {number}
     * @memberof DailyBreakdown
     */
    expense: number;
}

/**
 * Check if a given object implements the DailyBreakdown interface.
 */
export function instanceOfDailyBreakdown(value: object): value is DailyBreakdown {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    if (!('expense' in value) || value['expense'] === undefined) return false;
    return true;
}

export function DailyBreakdownFromJSON(json: any): DailyBreakdown {
    return DailyBreakdownFromJSONTyped(json, false);
}

export function DailyBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'revenue': json['revenue'],
        'expense': json['expense'],
    };
}

export function DailyBreakdownToJSON(json: any): DailyBreakdown {
    return DailyBreakdownToJSONTyped(json, false);
}

export function DailyBreakdownToJSONTyped(value?: DailyBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'revenue': value['revenue'],
        'expense': value['expense'],
    };
}

