/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateInput
 */
export interface DateInput {
    /**
     * 
     * @type {string}
     * @memberof DateInput
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof DateInput
     */
    time: string;
}

/**
 * Check if a given object implements the DateInput interface.
 */
export function instanceOfDateInput(value: object): value is DateInput {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function DateInputFromJSON(json: any): DateInput {
    return DateInputFromJSONTyped(json, false);
}

export function DateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'time': json['time'],
    };
}

export function DateInputToJSON(json: any): DateInput {
    return DateInputToJSONTyped(json, false);
}

export function DateInputToJSONTyped(value?: DateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'time': value['time'],
    };
}

