/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoricalData } from './HistoricalData';
import {
    HistoricalDataFromJSON,
    HistoricalDataFromJSONTyped,
    HistoricalDataToJSON,
    HistoricalDataToJSONTyped,
} from './HistoricalData';

/**
 * 
 * @export
 * @interface EventForecastResponse
 */
export interface EventForecastResponse {
    /**
     * 
     * @type {string}
     * @memberof EventForecastResponse
     */
    eventId: string;
    /**
     * 
     * @type {number}
     * @memberof EventForecastResponse
     */
    currentSales: number;
    /**
     * 
     * @type {number}
     * @memberof EventForecastResponse
     */
    predictedAttendance: number;
    /**
     * 
     * @type {Array<HistoricalData>}
     * @memberof EventForecastResponse
     */
    historicalData: Array<HistoricalData>;
}

/**
 * Check if a given object implements the EventForecastResponse interface.
 */
export function instanceOfEventForecastResponse(value: object): value is EventForecastResponse {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('currentSales' in value) || value['currentSales'] === undefined) return false;
    if (!('predictedAttendance' in value) || value['predictedAttendance'] === undefined) return false;
    if (!('historicalData' in value) || value['historicalData'] === undefined) return false;
    return true;
}

export function EventForecastResponseFromJSON(json: any): EventForecastResponse {
    return EventForecastResponseFromJSONTyped(json, false);
}

export function EventForecastResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventForecastResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'currentSales': json['current_sales'],
        'predictedAttendance': json['predicted_attendance'],
        'historicalData': ((json['historical_data'] as Array<any>).map(HistoricalDataFromJSON)),
    };
}

export function EventForecastResponseToJSON(json: any): EventForecastResponse {
    return EventForecastResponseToJSONTyped(json, false);
}

export function EventForecastResponseToJSONTyped(value?: EventForecastResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'current_sales': value['currentSales'],
        'predicted_attendance': value['predictedAttendance'],
        'historical_data': ((value['historicalData'] as Array<any>).map(HistoricalDataToJSON)),
    };
}

