/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObservationInput } from './ObservationInput';
import {
    ObservationInputFromJSON,
    ObservationInputFromJSONTyped,
    ObservationInputToJSON,
    ObservationInputToJSONTyped,
} from './ObservationInput';
import type { SalesData } from './SalesData';
import {
    SalesDataFromJSON,
    SalesDataFromJSONTyped,
    SalesDataToJSON,
    SalesDataToJSONTyped,
} from './SalesData';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';

/**
 * 
 * @export
 * @interface EventDetailsResponse
 */
export interface EventDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof EventDetailsResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailsResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailsResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailsResponse
     */
    time: string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailsResponse
     */
    location: string;
    /**
     * 
     * @type {EventStatus}
     * @memberof EventDetailsResponse
     */
    status: EventStatus;
    /**
     * 
     * @type {SalesData}
     * @memberof EventDetailsResponse
     */
    sales: SalesData;
    /**
     * 
     * @type {Array<ObservationInput>}
     * @memberof EventDetailsResponse
     */
    observations: Array<ObservationInput>;
}



/**
 * Check if a given object implements the EventDetailsResponse interface.
 */
export function instanceOfEventDetailsResponse(value: object): value is EventDetailsResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sales' in value) || value['sales'] === undefined) return false;
    if (!('observations' in value) || value['observations'] === undefined) return false;
    return true;
}

export function EventDetailsResponseFromJSON(json: any): EventDetailsResponse {
    return EventDetailsResponseFromJSONTyped(json, false);
}

export function EventDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'date': json['date'],
        'time': json['time'],
        'location': json['location'],
        'status': EventStatusFromJSON(json['status']),
        'sales': SalesDataFromJSON(json['sales']),
        'observations': ((json['observations'] as Array<any>).map(ObservationInputFromJSON)),
    };
}

export function EventDetailsResponseToJSON(json: any): EventDetailsResponse {
    return EventDetailsResponseToJSONTyped(json, false);
}

export function EventDetailsResponseToJSONTyped(value?: EventDetailsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'date': value['date'],
        'time': value['time'],
        'location': value['location'],
        'status': EventStatusToJSON(value['status']),
        'sales': SalesDataToJSON(value['sales']),
        'observations': ((value['observations'] as Array<any>).map(ObservationInputToJSON)),
    };
}

