/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoricalData
 */
export interface HistoricalData {
    /**
     * 
     * @type {string}
     * @memberof HistoricalData
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof HistoricalData
     */
    count: number;
}

/**
 * Check if a given object implements the HistoricalData interface.
 */
export function instanceOfHistoricalData(value: object): value is HistoricalData {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function HistoricalDataFromJSON(json: any): HistoricalData {
    return HistoricalDataFromJSONTyped(json, false);
}

export function HistoricalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoricalData {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'count': json['count'],
    };
}

export function HistoricalDataToJSON(json: any): HistoricalData {
    return HistoricalDataToJSONTyped(json, false);
}

export function HistoricalDataToJSONTyped(value?: HistoricalData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'count': value['count'],
    };
}

