/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HourlyBreakdownResponse
 */
export interface HourlyBreakdownResponse {
    /**
     * 
     * @type {number}
     * @memberof HourlyBreakdownResponse
     */
    hour: number;
    /**
     * 
     * @type {number}
     * @memberof HourlyBreakdownResponse
     */
    revenue: number;
    /**
     * 
     * @type {number}
     * @memberof HourlyBreakdownResponse
     */
    transactions: number;
}

/**
 * Check if a given object implements the HourlyBreakdownResponse interface.
 */
export function instanceOfHourlyBreakdownResponse(value: object): value is HourlyBreakdownResponse {
    if (!('hour' in value) || value['hour'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function HourlyBreakdownResponseFromJSON(json: any): HourlyBreakdownResponse {
    return HourlyBreakdownResponseFromJSONTyped(json, false);
}

export function HourlyBreakdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HourlyBreakdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hour': json['hour'],
        'revenue': json['revenue'],
        'transactions': json['transactions'],
    };
}

export function HourlyBreakdownResponseToJSON(json: any): HourlyBreakdownResponse {
    return HourlyBreakdownResponseToJSONTyped(json, false);
}

export function HourlyBreakdownResponseToJSONTyped(value?: HourlyBreakdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hour': value['hour'],
        'revenue': value['revenue'],
        'transactions': value['transactions'],
    };
}

