/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ItemStatus = {
    Active: 'active',
    Closed: 'closed'
} as const;
export type ItemStatus = typeof ItemStatus[keyof typeof ItemStatus];


export function instanceOfItemStatus(value: any): boolean {
    for (const key in ItemStatus) {
        if (Object.prototype.hasOwnProperty.call(ItemStatus, key)) {
            if (ItemStatus[key as keyof typeof ItemStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ItemStatusFromJSON(json: any): ItemStatus {
    return ItemStatusFromJSONTyped(json, false);
}

export function ItemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemStatus {
    return json as ItemStatus;
}

export function ItemStatusToJSON(value?: ItemStatus | null): any {
    return value as any;
}

export function ItemStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ItemStatus {
    return value as ItemStatus;
}

