/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemSaleDetail
 */
export interface ItemSaleDetail {
    /**
     * 
     * @type {string}
     * @memberof ItemSaleDetail
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ItemSaleDetail
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSaleDetail
     */
    quantitySold: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSaleDetail
     */
    revenue: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSaleDetail
     */
    remainingStock: number;
}

/**
 * Check if a given object implements the ItemSaleDetail interface.
 */
export function instanceOfItemSaleDetail(value: object): value is ItemSaleDetail {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantitySold' in value) || value['quantitySold'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    if (!('remainingStock' in value) || value['remainingStock'] === undefined) return false;
    return true;
}

export function ItemSaleDetailFromJSON(json: any): ItemSaleDetail {
    return ItemSaleDetailFromJSONTyped(json, false);
}

export function ItemSaleDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemSaleDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'quantitySold': json['quantity_sold'],
        'revenue': json['revenue'],
        'remainingStock': json['remaining_stock'],
    };
}

export function ItemSaleDetailToJSON(json: any): ItemSaleDetail {
    return ItemSaleDetailToJSONTyped(json, false);
}

export function ItemSaleDetailToJSONTyped(value?: ItemSaleDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price': value['price'],
        'quantity_sold': value['quantitySold'],
        'revenue': value['revenue'],
        'remaining_stock': value['remainingStock'],
    };
}

