/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemSaleDetail } from './ItemSaleDetail';
import {
    ItemSaleDetailFromJSON,
    ItemSaleDetailFromJSONTyped,
    ItemSaleDetailToJSON,
    ItemSaleDetailToJSONTyped,
} from './ItemSaleDetail';

/**
 * 
 * @export
 * @interface ItemSales
 */
export interface ItemSales {
    /**
     * 
     * @type {number}
     * @memberof ItemSales
     */
    totalRevenue: number;
    /**
     * 
     * @type {Array<ItemSaleDetail>}
     * @memberof ItemSales
     */
    details: Array<ItemSaleDetail>;
}

/**
 * Check if a given object implements the ItemSales interface.
 */
export function instanceOfItemSales(value: object): value is ItemSales {
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function ItemSalesFromJSON(json: any): ItemSales {
    return ItemSalesFromJSONTyped(json, false);
}

export function ItemSalesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemSales {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRevenue': json['total_revenue'],
        'details': ((json['details'] as Array<any>).map(ItemSaleDetailFromJSON)),
    };
}

export function ItemSalesToJSON(json: any): ItemSales {
    return ItemSalesToJSONTyped(json, false);
}

export function ItemSalesToJSONTyped(value?: ItemSales | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_revenue': value['totalRevenue'],
        'details': ((value['details'] as Array<any>).map(ItemSaleDetailToJSON)),
    };
}

