/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemCustom
 */
export interface ItemCustom {
    /**
     * 
     * @type {string}
     * @memberof ItemCustom
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ItemCustom
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCustom
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof ItemCustom
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ItemCustom
     */
    quantitySold: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCustom
     */
    totalRevenue: number;
    /**
     * 
     * @type {Date}
     * @memberof ItemCustom
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ItemCustom interface.
 */
export function instanceOfItemCustom(value: object): value is ItemCustom {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('quantitySold' in value) || value['quantitySold'] === undefined) return false;
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ItemCustomFromJSON(json: any): ItemCustom {
    return ItemCustomFromJSONTyped(json, false);
}

export function ItemCustomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemCustom {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'quantity': json['quantity'],
        'price': json['price'],
        'id': json['id'],
        'quantitySold': json['quantity_sold'],
        'totalRevenue': json['total_revenue'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ItemCustomToJSON(json: any): ItemCustom {
    return ItemCustomToJSONTyped(json, false);
}

export function ItemCustomToJSONTyped(value?: ItemCustom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'quantity': value['quantity'],
        'price': value['price'],
        'id': value['id'],
        'quantity_sold': value['quantitySold'],
        'total_revenue': value['totalRevenue'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

