/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemResponse
 */
export interface ItemResponse {
    /**
     * 
     * @type {string}
     * @memberof ItemResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ItemResponse
     */
    totalQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof ItemResponse
     */
    totalRevenue: number;
}

/**
 * Check if a given object implements the ItemResponse interface.
 */
export function instanceOfItemResponse(value: object): value is ItemResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('totalQuantity' in value) || value['totalQuantity'] === undefined) return false;
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    return true;
}

export function ItemResponseFromJSON(json: any): ItemResponse {
    return ItemResponseFromJSONTyped(json, false);
}

export function ItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'totalQuantity': json['total_quantity'],
        'totalRevenue': json['total_revenue'],
    };
}

export function ItemResponseToJSON(json: any): ItemResponse {
    return ItemResponseToJSONTyped(json, false);
}

export function ItemResponseToJSONTyped(value?: ItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'total_quantity': value['totalQuantity'],
        'total_revenue': value['totalRevenue'],
    };
}

