/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LowStockItemResponse
 */
export interface LowStockItemResponse {
    /**
     * 
     * @type {string}
     * @memberof LowStockItemResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LowStockItemResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LowStockItemResponse
     */
    currentQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof LowStockItemResponse
     */
    price: number;
}

/**
 * Check if a given object implements the LowStockItemResponse interface.
 */
export function instanceOfLowStockItemResponse(value: object): value is LowStockItemResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currentQuantity' in value) || value['currentQuantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function LowStockItemResponseFromJSON(json: any): LowStockItemResponse {
    return LowStockItemResponseFromJSONTyped(json, false);
}

export function LowStockItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LowStockItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'currentQuantity': json['current_quantity'],
        'price': json['price'],
    };
}

export function LowStockItemResponseToJSON(json: any): LowStockItemResponse {
    return LowStockItemResponseToJSONTyped(json, false);
}

export function LowStockItemResponseToJSONTyped(value?: LowStockItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'current_quantity': value['currentQuantity'],
        'price': value['price'],
    };
}

