/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeetingBase
 */
export interface MeetingBase {
    /**
     * 
     * @type {string}
     * @memberof MeetingBase
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingBase
     */
    time: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingBase
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingBase
     */
    agenda: string;
}

/**
 * Check if a given object implements the MeetingBase interface.
 */
export function instanceOfMeetingBase(value: object): value is MeetingBase {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('agenda' in value) || value['agenda'] === undefined) return false;
    return true;
}

export function MeetingBaseFromJSON(json: any): MeetingBase {
    return MeetingBaseFromJSONTyped(json, false);
}

export function MeetingBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingBase {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'time': json['time'],
        'location': json['location'],
        'agenda': json['agenda'],
    };
}

export function MeetingBaseToJSON(json: any): MeetingBase {
    return MeetingBaseToJSONTyped(json, false);
}

export function MeetingBaseToJSONTyped(value?: MeetingBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'time': value['time'],
        'location': value['location'],
        'agenda': value['agenda'],
    };
}

