/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meeting
 */
export interface Meeting {
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    time: string;
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    agenda: string;
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    id: string;
}

/**
 * Check if a given object implements the Meeting interface.
 */
export function instanceOfMeeting(value: object): value is Meeting {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('agenda' in value) || value['agenda'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MeetingFromJSON(json: any): Meeting {
    return MeetingFromJSONTyped(json, false);
}

export function MeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meeting {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'time': json['time'],
        'location': json['location'],
        'agenda': json['agenda'],
        'id': json['id'],
    };
}

export function MeetingToJSON(json: any): Meeting {
    return MeetingToJSONTyped(json, false);
}

export function MeetingToJSONTyped(value?: Meeting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'time': value['time'],
        'location': value['location'],
        'agenda': value['agenda'],
        'id': value['id'],
    };
}

