/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meeting } from './Meeting';
import {
    MeetingFromJSON,
    MeetingFromJSONTyped,
    MeetingToJSON,
    MeetingToJSONTyped,
} from './Meeting';

/**
 * 
 * @export
 * @interface MeetingList
 */
export interface MeetingList {
    /**
     * 
     * @type {Array<Meeting>}
     * @memberof MeetingList
     */
    meetings: Array<Meeting>;
}

/**
 * Check if a given object implements the MeetingList interface.
 */
export function instanceOfMeetingList(value: object): value is MeetingList {
    if (!('meetings' in value) || value['meetings'] === undefined) return false;
    return true;
}

export function MeetingListFromJSON(json: any): MeetingList {
    return MeetingListFromJSONTyped(json, false);
}

export function MeetingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingList {
    if (json == null) {
        return json;
    }
    return {
        
        'meetings': ((json['meetings'] as Array<any>).map(MeetingFromJSON)),
    };
}

export function MeetingListToJSON(json: any): MeetingList {
    return MeetingListToJSONTyped(json, false);
}

export function MeetingListToJSONTyped(value?: MeetingList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meetings': ((value['meetings'] as Array<any>).map(MeetingToJSON)),
    };
}

