/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionResponse } from './TransactionResponse';
import {
    TransactionResponseFromJSON,
    TransactionResponseFromJSONTyped,
    TransactionResponseToJSON,
    TransactionResponseToJSONTyped,
} from './TransactionResponse';

/**
 * 
 * @export
 * @interface MonthlyFinancialReport
 */
export interface MonthlyFinancialReport {
    /**
     * 
     * @type {string}
     * @memberof MonthlyFinancialReport
     */
    month: string;
    /**
     * 
     * @type {number}
     * @memberof MonthlyFinancialReport
     */
    totalRevenue: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyFinancialReport
     */
    totalExpenses: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyFinancialReport
     */
    netIncome: number;
    /**
     * 
     * @type {Array<TransactionResponse>}
     * @memberof MonthlyFinancialReport
     */
    transactions: Array<TransactionResponse>;
}

/**
 * Check if a given object implements the MonthlyFinancialReport interface.
 */
export function instanceOfMonthlyFinancialReport(value: object): value is MonthlyFinancialReport {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('totalExpenses' in value) || value['totalExpenses'] === undefined) return false;
    if (!('netIncome' in value) || value['netIncome'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function MonthlyFinancialReportFromJSON(json: any): MonthlyFinancialReport {
    return MonthlyFinancialReportFromJSONTyped(json, false);
}

export function MonthlyFinancialReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyFinancialReport {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'],
        'totalRevenue': json['total_revenue'],
        'totalExpenses': json['total_expenses'],
        'netIncome': json['net_income'],
        'transactions': ((json['transactions'] as Array<any>).map(TransactionResponseFromJSON)),
    };
}

export function MonthlyFinancialReportToJSON(json: any): MonthlyFinancialReport {
    return MonthlyFinancialReportToJSONTyped(json, false);
}

export function MonthlyFinancialReportToJSONTyped(value?: MonthlyFinancialReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'total_revenue': value['totalRevenue'],
        'total_expenses': value['totalExpenses'],
        'net_income': value['netIncome'],
        'transactions': ((value['transactions'] as Array<any>).map(TransactionResponseToJSON)),
    };
}

