/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObservationInput
 */
export interface ObservationInput {
    /**
     * 
     * @type {string}
     * @memberof ObservationInput
     */
    content: string;
}

/**
 * Check if a given object implements the ObservationInput interface.
 */
export function instanceOfObservationInput(value: object): value is ObservationInput {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ObservationInputFromJSON(json: any): ObservationInput {
    return ObservationInputFromJSONTyped(json, false);
}

export function ObservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function ObservationInputToJSON(json: any): ObservationInput {
    return ObservationInputToJSONTyped(json, false);
}

export function ObservationInputToJSONTyped(value?: ObservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

