/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordChangeRequest
 */
export interface PasswordChangeRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordChangeRequest interface.
 */
export function instanceOfPasswordChangeRequest(value: object): value is PasswordChangeRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function PasswordChangeRequestFromJSON(json: any): PasswordChangeRequest {
    return PasswordChangeRequestFromJSONTyped(json, false);
}

export function PasswordChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordChangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
    };
}

export function PasswordChangeRequestToJSON(json: any): PasswordChangeRequest {
    return PasswordChangeRequestToJSONTyped(json, false);
}

export function PasswordChangeRequestToJSONTyped(value?: PasswordChangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
    };
}

