/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * 
     * @type {number}
     * @memberof Period
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof Period
     */
    month: number;
}

/**
 * Check if a given object implements the Period interface.
 */
export function instanceOfPeriod(value: object): value is Period {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    return true;
}

export function PeriodFromJSON(json: any): Period {
    return PeriodFromJSONTyped(json, false);
}

export function PeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Period {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'month': json['month'],
    };
}

export function PeriodToJSON(json: any): Period {
    return PeriodToJSONTyped(json, false);
}

export function PeriodToJSONTyped(value?: Period | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
    };
}

