/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceQuantity
 */
export interface PriceQuantity {
    /**
     * 
     * @type {number}
     * @memberof PriceQuantity
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof PriceQuantity
     */
    price: number;
}

/**
 * Check if a given object implements the PriceQuantity interface.
 */
export function instanceOfPriceQuantity(value: object): value is PriceQuantity {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PriceQuantityFromJSON(json: any): PriceQuantity {
    return PriceQuantityFromJSONTyped(json, false);
}

export function PriceQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceQuantity {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'price': json['price'],
    };
}

export function PriceQuantityToJSON(json: any): PriceQuantity {
    return PriceQuantityToJSONTyped(json, false);
}

export function PriceQuantityToJSONTyped(value?: PriceQuantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'price': value['price'],
    };
}

