/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RescheduleEventResponse
 */
export interface RescheduleEventResponse {
    /**
     * 
     * @type {string}
     * @memberof RescheduleEventResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RescheduleEventResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof RescheduleEventResponse
     */
    time: string;
}

/**
 * Check if a given object implements the RescheduleEventResponse interface.
 */
export function instanceOfRescheduleEventResponse(value: object): value is RescheduleEventResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function RescheduleEventResponseFromJSON(json: any): RescheduleEventResponse {
    return RescheduleEventResponseFromJSONTyped(json, false);
}

export function RescheduleEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RescheduleEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'time': json['time'],
    };
}

export function RescheduleEventResponseToJSON(json: any): RescheduleEventResponse {
    return RescheduleEventResponseToJSONTyped(json, false);
}

export function RescheduleEventResponseToJSONTyped(value?: RescheduleEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'],
        'time': value['time'],
    };
}

