/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventRevenueRanking } from './EventRevenueRanking';
import {
    EventRevenueRankingFromJSON,
    EventRevenueRankingFromJSONTyped,
    EventRevenueRankingToJSON,
    EventRevenueRankingToJSONTyped,
} from './EventRevenueRanking';

/**
 * 
 * @export
 * @interface RevenueRankingResponse
 */
export interface RevenueRankingResponse {
    /**
     * 
     * @type {Array<EventRevenueRanking>}
     * @memberof RevenueRankingResponse
     */
    events: Array<EventRevenueRanking>;
}

/**
 * Check if a given object implements the RevenueRankingResponse interface.
 */
export function instanceOfRevenueRankingResponse(value: object): value is RevenueRankingResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function RevenueRankingResponseFromJSON(json: any): RevenueRankingResponse {
    return RevenueRankingResponseFromJSONTyped(json, false);
}

export function RevenueRankingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevenueRankingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(EventRevenueRankingFromJSON)),
    };
}

export function RevenueRankingResponseToJSON(json: any): RevenueRankingResponse {
    return RevenueRankingResponseToJSONTyped(json, false);
}

export function RevenueRankingResponseToJSONTyped(value?: RevenueRankingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(EventRevenueRankingToJSON)),
    };
}

