/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaleCreate
 */
export interface SaleCreate {
    /**
     * 
     * @type {number}
     * @memberof SaleCreate
     */
    quantitySold: number;
    /**
     * 
     * @type {string}
     * @memberof SaleCreate
     */
    itemId: string;
}

/**
 * Check if a given object implements the SaleCreate interface.
 */
export function instanceOfSaleCreate(value: object): value is SaleCreate {
    if (!('quantitySold' in value) || value['quantitySold'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function SaleCreateFromJSON(json: any): SaleCreate {
    return SaleCreateFromJSONTyped(json, false);
}

export function SaleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quantitySold': json['quantity_sold'],
        'itemId': json['item_id'],
    };
}

export function SaleCreateToJSON(json: any): SaleCreate {
    return SaleCreateToJSONTyped(json, false);
}

export function SaleCreateToJSONTyped(value?: SaleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity_sold': value['quantitySold'],
        'item_id': value['itemId'],
    };
}

