/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaleItem
 */
export interface SaleItem {
    /**
     * 
     * @type {string}
     * @memberof SaleItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SaleItem
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof SaleItem
     */
    revenue: number;
}

/**
 * Check if a given object implements the SaleItem interface.
 */
export function instanceOfSaleItem(value: object): value is SaleItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    return true;
}

export function SaleItemFromJSON(json: any): SaleItem {
    return SaleItemFromJSONTyped(json, false);
}

export function SaleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'quantity': json['quantity'],
        'revenue': json['revenue'],
    };
}

export function SaleItemToJSON(json: any): SaleItem {
    return SaleItemToJSONTyped(json, false);
}

export function SaleItemToJSONTyped(value?: SaleItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'quantity': value['quantity'],
        'revenue': value['revenue'],
    };
}

