/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface SalesByPaymentMethod
 */
export interface SalesByPaymentMethod {
    /**
     * 
     * @type {PaymentMethod}
     * @memberof SalesByPaymentMethod
     */
    method: PaymentMethod;
    /**
     * 
     * @type {number}
     * @memberof SalesByPaymentMethod
     */
    amount: number;
}



/**
 * Check if a given object implements the SalesByPaymentMethod interface.
 */
export function instanceOfSalesByPaymentMethod(value: object): value is SalesByPaymentMethod {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function SalesByPaymentMethodFromJSON(json: any): SalesByPaymentMethod {
    return SalesByPaymentMethodFromJSONTyped(json, false);
}

export function SalesByPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesByPaymentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'method': PaymentMethodFromJSON(json['method']),
        'amount': json['amount'],
    };
}

export function SalesByPaymentMethodToJSON(json: any): SalesByPaymentMethod {
    return SalesByPaymentMethodToJSONTyped(json, false);
}

export function SalesByPaymentMethodToJSONTyped(value?: SalesByPaymentMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': PaymentMethodToJSON(value['method']),
        'amount': value['amount'],
    };
}

