/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HourlyBreakdownResponse } from './HourlyBreakdownResponse';
import {
    HourlyBreakdownResponseFromJSON,
    HourlyBreakdownResponseFromJSONTyped,
    HourlyBreakdownResponseToJSON,
    HourlyBreakdownResponseToJSONTyped,
} from './HourlyBreakdownResponse';

/**
 * 
 * @export
 * @interface SalesResponse
 */
export interface SalesResponse {
    /**
     * 
     * @type {Date}
     * @memberof SalesResponse
     */
    date: Date;
    /**
     * 
     * @type {Array<HourlyBreakdownResponse>}
     * @memberof SalesResponse
     */
    hourlyBreakdown: Array<HourlyBreakdownResponse>;
}

/**
 * Check if a given object implements the SalesResponse interface.
 */
export function instanceOfSalesResponse(value: object): value is SalesResponse {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('hourlyBreakdown' in value) || value['hourlyBreakdown'] === undefined) return false;
    return true;
}

export function SalesResponseFromJSON(json: any): SalesResponse {
    return SalesResponseFromJSONTyped(json, false);
}

export function SalesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'hourlyBreakdown': ((json['hourly_breakdown'] as Array<any>).map(HourlyBreakdownResponseFromJSON)),
    };
}

export function SalesResponseToJSON(json: any): SalesResponse {
    return SalesResponseToJSONTyped(json, false);
}

export function SalesResponseToJSONTyped(value?: SalesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString()),
        'hourly_breakdown': ((value['hourlyBreakdown'] as Array<any>).map(HourlyBreakdownResponseToJSON)),
    };
}

