/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchEventsResponse
 */
export interface SearchEventsResponse {
    /**
     * 
     * @type {number}
     * @memberof SearchEventsResponse
     */
    totalResults: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchEventsResponse
     */
    events: Array<string>;
}

/**
 * Check if a given object implements the SearchEventsResponse interface.
 */
export function instanceOfSearchEventsResponse(value: object): value is SearchEventsResponse {
    if (!('totalResults' in value) || value['totalResults'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function SearchEventsResponseFromJSON(json: any): SearchEventsResponse {
    return SearchEventsResponseFromJSONTyped(json, false);
}

export function SearchEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResults': json['total_results'],
        'events': json['events'],
    };
}

export function SearchEventsResponseToJSON(json: any): SearchEventsResponse {
    return SearchEventsResponseToJSONTyped(json, false);
}

export function SearchEventsResponseToJSONTyped(value?: SearchEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_results': value['totalResults'],
        'events': value['events'],
    };
}

