/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StandaloneItemUpdate
 */
export interface StandaloneItemUpdate {
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemUpdate
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemUpdate
     */
    quantity?: number | null;
}

/**
 * Check if a given object implements the StandaloneItemUpdate interface.
 */
export function instanceOfStandaloneItemUpdate(value: object): value is StandaloneItemUpdate {
    return true;
}

export function StandaloneItemUpdateFromJSON(json: any): StandaloneItemUpdate {
    return StandaloneItemUpdateFromJSONTyped(json, false);
}

export function StandaloneItemUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandaloneItemUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function StandaloneItemUpdateToJSON(json: any): StandaloneItemUpdate {
    return StandaloneItemUpdateToJSONTyped(json, false);
}

export function StandaloneItemUpdateToJSONTyped(value?: StandaloneItemUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'quantity': value['quantity'],
    };
}

