/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface StandaloneItemSaleCreate
 */
export interface StandaloneItemSaleCreate {
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemSaleCreate
     */
    quantity: number;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof StandaloneItemSaleCreate
     */
    paymentMethod: PaymentMethod;
}



/**
 * Check if a given object implements the StandaloneItemSaleCreate interface.
 */
export function instanceOfStandaloneItemSaleCreate(value: object): value is StandaloneItemSaleCreate {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function StandaloneItemSaleCreateFromJSON(json: any): StandaloneItemSaleCreate {
    return StandaloneItemSaleCreateFromJSONTyped(json, false);
}

export function StandaloneItemSaleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandaloneItemSaleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'paymentMethod': PaymentMethodFromJSON(json['payment_method']),
    };
}

export function StandaloneItemSaleCreateToJSON(json: any): StandaloneItemSaleCreate {
    return StandaloneItemSaleCreateToJSONTyped(json, false);
}

export function StandaloneItemSaleCreateToJSONTyped(value?: StandaloneItemSaleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'payment_method': PaymentMethodToJSON(value['paymentMethod']),
    };
}

