/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StandaloneItemCreate
 */
export interface StandaloneItemCreate {
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemCreate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemCreate
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemCreate
     */
    quantity: number;
}

/**
 * Check if a given object implements the StandaloneItemCreate interface.
 */
export function instanceOfStandaloneItemCreate(value: object): value is StandaloneItemCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function StandaloneItemCreateFromJSON(json: any): StandaloneItemCreate {
    return StandaloneItemCreateFromJSONTyped(json, false);
}

export function StandaloneItemCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandaloneItemCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'quantity': json['quantity'],
    };
}

export function StandaloneItemCreateToJSON(json: any): StandaloneItemCreate {
    return StandaloneItemCreateToJSONTyped(json, false);
}

export function StandaloneItemCreateToJSONTyped(value?: StandaloneItemCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'quantity': value['quantity'],
    };
}

