/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface StandaloneItemSale
 */
export interface StandaloneItemSale {
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemSale
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StandaloneItemSale
     */
    itemId: string;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemSale
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof StandaloneItemSale
     */
    totalAmount: number;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof StandaloneItemSale
     */
    paymentMethod: PaymentMethod;
    /**
     * 
     * @type {Date}
     * @memberof StandaloneItemSale
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the StandaloneItemSale interface.
 */
export function instanceOfStandaloneItemSale(value: object): value is StandaloneItemSale {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function StandaloneItemSaleFromJSON(json: any): StandaloneItemSale {
    return StandaloneItemSaleFromJSONTyped(json, false);
}

export function StandaloneItemSaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandaloneItemSale {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['item_id'],
        'quantity': json['quantity'],
        'totalAmount': json['total_amount'],
        'paymentMethod': PaymentMethodFromJSON(json['payment_method']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function StandaloneItemSaleToJSON(json: any): StandaloneItemSale {
    return StandaloneItemSaleToJSONTyped(json, false);
}

export function StandaloneItemSaleToJSONTyped(value?: StandaloneItemSale | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'item_id': value['itemId'],
        'quantity': value['quantity'],
        'total_amount': value['totalAmount'],
        'payment_method': PaymentMethodToJSON(value['paymentMethod']),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

