/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketSaleDetail
 */
export interface TicketSaleDetail {
    /**
     * 
     * @type {string}
     * @memberof TicketSaleDetail
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof TicketSaleDetail
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof TicketSaleDetail
     */
    quantitySold: number;
    /**
     * 
     * @type {number}
     * @memberof TicketSaleDetail
     */
    revenue: number;
}

/**
 * Check if a given object implements the TicketSaleDetail interface.
 */
export function instanceOfTicketSaleDetail(value: object): value is TicketSaleDetail {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantitySold' in value) || value['quantitySold'] === undefined) return false;
    if (!('revenue' in value) || value['revenue'] === undefined) return false;
    return true;
}

export function TicketSaleDetailFromJSON(json: any): TicketSaleDetail {
    return TicketSaleDetailFromJSONTyped(json, false);
}

export function TicketSaleDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketSaleDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'price': json['price'],
        'quantitySold': json['quantity_sold'],
        'revenue': json['revenue'],
    };
}

export function TicketSaleDetailToJSON(json: any): TicketSaleDetail {
    return TicketSaleDetailToJSONTyped(json, false);
}

export function TicketSaleDetailToJSONTyped(value?: TicketSaleDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'price': value['price'],
        'quantity_sold': value['quantitySold'],
        'revenue': value['revenue'],
    };
}

