/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketSaleDetail } from './TicketSaleDetail';
import {
    TicketSaleDetailFromJSON,
    TicketSaleDetailFromJSONTyped,
    TicketSaleDetailToJSON,
    TicketSaleDetailToJSONTyped,
} from './TicketSaleDetail';

/**
 * 
 * @export
 * @interface TicketSales
 */
export interface TicketSales {
    /**
     * 
     * @type {number}
     * @memberof TicketSales
     */
    totalRevenue: number;
    /**
     * 
     * @type {Array<TicketSaleDetail>}
     * @memberof TicketSales
     */
    details: Array<TicketSaleDetail>;
}

/**
 * Check if a given object implements the TicketSales interface.
 */
export function instanceOfTicketSales(value: object): value is TicketSales {
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function TicketSalesFromJSON(json: any): TicketSales {
    return TicketSalesFromJSONTyped(json, false);
}

export function TicketSalesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketSales {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRevenue': json['total_revenue'],
        'details': ((json['details'] as Array<any>).map(TicketSaleDetailFromJSON)),
    };
}

export function TicketSalesToJSON(json: any): TicketSales {
    return TicketSalesToJSONTyped(json, false);
}

export function TicketSalesToJSONTyped(value?: TicketSales | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_revenue': value['totalRevenue'],
        'details': ((value['details'] as Array<any>).map(TicketSaleDetailToJSON)),
    };
}

