/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketSaleHistory } from './TicketSaleHistory';
import {
    TicketSaleHistoryFromJSON,
    TicketSaleHistoryFromJSONTyped,
    TicketSaleHistoryToJSON,
    TicketSaleHistoryToJSONTyped,
} from './TicketSaleHistory';

/**
 * 
 * @export
 * @interface TicketSalesHistoryResponse
 */
export interface TicketSalesHistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof TicketSalesHistoryResponse
     */
    eventId: string;
    /**
     * 
     * @type {number}
     * @memberof TicketSalesHistoryResponse
     */
    totalSales: number;
    /**
     * 
     * @type {number}
     * @memberof TicketSalesHistoryResponse
     */
    totalRevenue: number;
    /**
     * 
     * @type {Array<TicketSaleHistory>}
     * @memberof TicketSalesHistoryResponse
     */
    sales: Array<TicketSaleHistory>;
}

/**
 * Check if a given object implements the TicketSalesHistoryResponse interface.
 */
export function instanceOfTicketSalesHistoryResponse(value: object): value is TicketSalesHistoryResponse {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('totalSales' in value) || value['totalSales'] === undefined) return false;
    if (!('totalRevenue' in value) || value['totalRevenue'] === undefined) return false;
    if (!('sales' in value) || value['sales'] === undefined) return false;
    return true;
}

export function TicketSalesHistoryResponseFromJSON(json: any): TicketSalesHistoryResponse {
    return TicketSalesHistoryResponseFromJSONTyped(json, false);
}

export function TicketSalesHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketSalesHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'totalSales': json['total_sales'],
        'totalRevenue': json['total_revenue'],
        'sales': ((json['sales'] as Array<any>).map(TicketSaleHistoryFromJSON)),
    };
}

export function TicketSalesHistoryResponseToJSON(json: any): TicketSalesHistoryResponse {
    return TicketSalesHistoryResponseToJSONTyped(json, false);
}

export function TicketSalesHistoryResponseToJSONTyped(value?: TicketSalesHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'total_sales': value['totalSales'],
        'total_revenue': value['totalRevenue'],
        'sales': ((value['sales'] as Array<any>).map(TicketSaleHistoryToJSON)),
    };
}

