/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketCreate
 */
export interface TicketCreate {
    /**
     * 
     * @type {string}
     * @memberof TicketCreate
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof TicketCreate
     */
    price: number;
}

/**
 * Check if a given object implements the TicketCreate interface.
 */
export function instanceOfTicketCreate(value: object): value is TicketCreate {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function TicketCreateFromJSON(json: any): TicketCreate {
    return TicketCreateFromJSONTyped(json, false);
}

export function TicketCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'price': json['price'],
    };
}

export function TicketCreateToJSON(json: any): TicketCreate {
    return TicketCreateToJSONTyped(json, false);
}

export function TicketCreateToJSONTyped(value?: TicketCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'price': value['price'],
    };
}

