/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketSaleHistory
 */
export interface TicketSaleHistory {
    /**
     * 
     * @type {string}
     * @memberof TicketSaleHistory
     */
    saleId: string;
    /**
     * 
     * @type {string}
     * @memberof TicketSaleHistory
     */
    ticketType: string;
    /**
     * 
     * @type {number}
     * @memberof TicketSaleHistory
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof TicketSaleHistory
     */
    totalAmount: number;
    /**
     * 
     * @type {Date}
     * @memberof TicketSaleHistory
     */
    purchaseDate: Date;
}

/**
 * Check if a given object implements the TicketSaleHistory interface.
 */
export function instanceOfTicketSaleHistory(value: object): value is TicketSaleHistory {
    if (!('saleId' in value) || value['saleId'] === undefined) return false;
    if (!('ticketType' in value) || value['ticketType'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    if (!('purchaseDate' in value) || value['purchaseDate'] === undefined) return false;
    return true;
}

export function TicketSaleHistoryFromJSON(json: any): TicketSaleHistory {
    return TicketSaleHistoryFromJSONTyped(json, false);
}

export function TicketSaleHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketSaleHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'saleId': json['sale_id'],
        'ticketType': json['ticket_type'],
        'quantity': json['quantity'],
        'totalAmount': json['total_amount'],
        'purchaseDate': (new Date(json['purchase_date'])),
    };
}

export function TicketSaleHistoryToJSON(json: any): TicketSaleHistory {
    return TicketSaleHistoryToJSONTyped(json, false);
}

export function TicketSaleHistoryToJSONTyped(value?: TicketSaleHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sale_id': value['saleId'],
        'ticket_type': value['ticketType'],
        'quantity': value['quantity'],
        'total_amount': value['totalAmount'],
        'purchase_date': ((value['purchaseDate']).toISOString()),
    };
}

