/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemResponse } from './ItemResponse';
import {
    ItemResponseFromJSON,
    ItemResponseFromJSONTyped,
    ItemResponseToJSON,
    ItemResponseToJSONTyped,
} from './ItemResponse';

/**
 * 
 * @export
 * @interface TopItemsResponse
 */
export interface TopItemsResponse {
    /**
     * 
     * @type {Array<ItemResponse>}
     * @memberof TopItemsResponse
     */
    items: Array<ItemResponse>;
}

/**
 * Check if a given object implements the TopItemsResponse interface.
 */
export function instanceOfTopItemsResponse(value: object): value is TopItemsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TopItemsResponseFromJSON(json: any): TopItemsResponse {
    return TopItemsResponseFromJSONTyped(json, false);
}

export function TopItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ItemResponseFromJSON)),
    };
}

export function TopItemsResponseToJSON(json: any): TopItemsResponse {
    return TopItemsResponseToJSONTyped(json, false);
}

export function TopItemsResponseToJSONTyped(value?: TopItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ItemResponseToJSON)),
    };
}

