/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionCategoryResponse
 */
export interface TransactionCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof TransactionCategoryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCategoryResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCategoryResponse
     */
    description: string | null;
}

/**
 * Check if a given object implements the TransactionCategoryResponse interface.
 */
export function instanceOfTransactionCategoryResponse(value: object): value is TransactionCategoryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function TransactionCategoryResponseFromJSON(json: any): TransactionCategoryResponse {
    return TransactionCategoryResponseFromJSONTyped(json, false);
}

export function TransactionCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function TransactionCategoryResponseToJSON(json: any): TransactionCategoryResponse {
    return TransactionCategoryResponseToJSONTyped(json, false);
}

export function TransactionCategoryResponseToJSONTyped(value?: TransactionCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

