/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionCategoryCreate
 */
export interface TransactionCategoryCreate {
    /**
     * 
     * @type {string}
     * @memberof TransactionCategoryCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCategoryCreate
     */
    description: string | null;
}

/**
 * Check if a given object implements the TransactionCategoryCreate interface.
 */
export function instanceOfTransactionCategoryCreate(value: object): value is TransactionCategoryCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function TransactionCategoryCreateFromJSON(json: any): TransactionCategoryCreate {
    return TransactionCategoryCreateFromJSONTyped(json, false);
}

export function TransactionCategoryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCategoryCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function TransactionCategoryCreateToJSON(json: any): TransactionCategoryCreate {
    return TransactionCategoryCreateToJSONTyped(json, false);
}

export function TransactionCategoryCreateToJSONTyped(value?: TransactionCategoryCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

