/* tslint:disable */
/* eslint-disable */
/**
 * Events Management API
 * This API provides comprehensive management of events, including detailed analytics, revenue tracking, rescheduling, cancellations, and insights into capacity and sales performance.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendingEvent
 */
export interface TrendingEvent {
    /**
     * 
     * @type {string}
     * @memberof TrendingEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrendingEvent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TrendingEvent
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof TrendingEvent
     */
    ticketSales: number;
}

/**
 * Check if a given object implements the TrendingEvent interface.
 */
export function instanceOfTrendingEvent(value: object): value is TrendingEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('ticketSales' in value) || value['ticketSales'] === undefined) return false;
    return true;
}

export function TrendingEventFromJSON(json: any): TrendingEvent {
    return TrendingEventFromJSONTyped(json, false);
}

export function TrendingEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'date': json['date'],
        'ticketSales': json['ticket_sales'],
    };
}

export function TrendingEventToJSON(json: any): TrendingEvent {
    return TrendingEventToJSONTyped(json, false);
}

export function TrendingEventToJSONTyped(value?: TrendingEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'date': value['date'],
        'ticket_sales': value['ticketSales'],
    };
}

